[project]
name = "mcp-server-v1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hb_W", email = "hugobarillasvi@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
mcp-server-v1 = "mcp_server_v1:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
